### ISSUE TITLE
Build issue in QT 5.15.3

### ISSUE THREAD

**Issue by merspieler** [albar965/littlenavmap#886]
I'm trying to create a package for NixOS 21.11 which uses QT 5.15.3 and marble 21.08.3.
When building lnm I get the following error. And idea how to fix this?
```
src/common/coordinateconverter.cpp:54:86: error: return type 'class Marble::GeoDataLatLonBox' is incomplete
   54 | Marble::GeoDataLatLonBox CoordinateConverter::toGdc(const atools::geo::Rect& coords) const
      |                                                                                      ^~~~~
src/common/coordinateconverter.cpp: In member function 'void CoordinateConverter::toGdc(const atools::geo::Rect&) const':
src/common/coordinateconverter.cpp:57:66: error: invalid use of incomplete type 'class Marble::GeoDataLatLonBox'
   57 |                           coords.getEast(), coords.getWest(), DEG);
      |                                                                  ^
In file included from src/common/coordinateconverter.cpp:18:
src/common/coordinateconverter.h:29:7: note: forward declaration of 'class Marble::GeoDataLatLonBox'
   29 | class GeoDataLatLonBox;
      |       ^~~~~~~~~~~~~~~~
src/common/coordinateconverter.cpp: In member function 'atools::geo::Rect CoordinateConverter::fromGdc(const Marble::GeoDataLatLonBox&) const':
src/common/coordinateconverter.cpp:62:15: error: invalid use of incomplete type 'const class Marble::GeoDataLatLonBox'
   62 |   return Rect(coords.west(DEG), coords.north(DEG), coords.east(DEG), coords.south(DEG));
      |               ^~~~~~
In file included from src/common/coordinateconverter.cpp:18:
src/common/coordinateconverter.h:29:7: note: forward declaration of 'class Marble::GeoDataLatLonBox'
   29 | class GeoDataLatLonBox;
      |       ^~~~~~~~~~~~~~~~
src/common/coordinateconverter.cpp:62:33: error: invalid use of incomplete type 'const class Marble::GeoDataLatLonBox'
   62 |   return Rect(coords.west(DEG), coords.north(DEG), coords.east(DEG), coords.south(DEG));
      |                                 ^~~~~~
In file included from src/common/coordinateconverter.cpp:18:
src/common/coordinateconverter.h:29:7: note: forward declaration of 'class Marble::GeoDataLatLonBox'
   29 | class GeoDataLatLonBox;
      |       ^~~~~~~~~~~~~~~~
src/common/coordinateconverter.cpp:62:52: error: invalid use of incomplete type 'const class Marble::GeoDataLatLonBox'
   62 |   return Rect(coords.west(DEG), coords.north(DEG), coords.east(DEG), coords.south(DEG));
      |                                                    ^~~~~~
In file included from src/common/coordinateconverter.cpp:18:
src/common/coordinateconverter.h:29:7: note: forward declaration of 'class Marble::GeoDataLatLonBox'
   29 | class GeoDataLatLonBox;
      |       ^~~~~~~~~~~~~~~~
src/common/coordinateconverter.cpp:62:70: error: invalid use of incomplete type 'const class Marble::GeoDataLatLonBox'
   62 |   return Rect(coords.west(DEG), coords.north(DEG), coords.east(DEG), coords.south(DEG));
```

**Comment by albar965** [comment]
You have to use this Marble here: https://github.com/albar965/marble
Branch `lnm/1.1`. This compiles with LNM `master` and `release/2.6`.

``` shell
mkdir $APROJECTS/marble
mkdir $APROJECTS/build-marble-release
cd $APROJECTS/build-marble-release

cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC_BUILD=TRUE -DQTONLY=TRUE -DBUILD_MARBLE_EXAMPLES=NO -DBUILD_INHIBIT_SCREENSAVER_PLUGIN=NO -DBUILD_MARBLE_APPS=NO -DBUILD_MARBLE_EXAMPLES=NO -DBUILD_MARBLE_TESTS=NO -DBUILD_MARBLE_TOOLS=NO -DBUILD_TESTING=NO -DBUILD_WITH_DBUS=NO -DMARBLE_EMPTY_MAPTHEME=YES -DMOBILE=NO -DWITH_DESIGNER_PLUGIN=NO -DWITH_Phonon=NO -DWITH_Qt5Location=NO -DWITH_Qt5Positioning=NO -DWITH_Qt5SerialPort=NO -DWITH_ZLIB=NO -DWITH_libgps=NO -DWITH_libshp=NO -DWITH_libwlocate=NO -DCMAKE_INSTALL_PREFIX=$APROJECTS/Marble-release -DEXEC_INSTALL_PREFIX=$APROJECTS/Marble-release -DCMAKE_PREFIX_PATH=/home/alex/Qt/5.12.11/gcc_64/ ../marble/

make 
make install
```

You have to adjust the `CMAKE_PREFIX_PATH` in the command line to your Qt location.

I have to use my own branch to add more features and fix bugs which would otherwise take ages through official channels.

**Comment by merspieler** [comment]
okay thanks

**Comment by merspieler** [comment]
oh, thanks for reminding me, that I still wanted to build this as nix package :D 

unfortunately, marble throws a bunch of errors:
```
/build/source/src/plugins/positionprovider/gpsd/GpsdPositionProviderPlugin.cpp:82:15: error: 'struct gps_data_t' has no member named 'status'
   82 |     if ( data.status == STATUS_NO_FIX || std::isnan( data.fix.longitude ) || std::isnan( data.fix.latitude ) )
      |               ^~~~~~
/build/source/src/plugins/positionprovider/gpsd/GpsdPositionProviderPlugin.cpp:82:25: error: 'STATUS_NO_FIX' was not declared in this scope; did you mean 'STATUS_RTK_FIX'?
   82 |     if ( data.status == STATUS_NO_FIX || std::isnan( data.fix.longitude ) || std::isnan( data.fix.latitude ) )
      |                         ^~~~~~~~~~~~~
      |                         STATUS_RTK_FIX
/build/source/src/plugins/positionprovider/gpsd/GpsdPositionProviderPlugin.cpp:116:25: error: no matching function for call to 'isnan(timespec_t&)'
  116 |         if ( !std::isnan( data.fix.time 
.....
/build/source/src/plugins/positionprovider/gpsd/GpsdPositionProviderPlugin.cpp:118:73: error: no match for 'operator*' (operand types are 'timespec_t' {aka 'timespec'} and 'int')
  118 |             m_timestamp = QDateTime::fromMSecsSinceEpoch( data.fix.time * 1000 );
      |                                                           ~~~~~~~~~~~~~ ^ ~~~~
      |                                                                    |      |
      |                                                                    |      int
      |                                                                    timespec_t {aka timespec}
```
[Full log](https://github.com/albar965/littlenavmap/files/9482860/marble.log)

**Comment by albar965** [comment]
Did you really disable GPS when running `cmake`? See command line above.
Do you compile Marble `branch lnm/1.1`?

**Comment by merspieler** [comment]
yes, latest commit off of the lnm/1.1 branch, see commit id above.
yes, I've missed the gps... with that in, there are still more errors:
```
src/connect/connectclient.cpp:609:105: warning: 'void QAbstractSocket::error(QAbstractSocket::SocketError)' is deprecated: Use QAbstractSocket::errorOccurred(QAbstractSocket::SocketError) instead [-Wdeprecated-declarations]
  609 |             static_cast<void (QAbstractSocket::*)(QAbstractSocket::SocketError)>(&QAbstractSocket::error),
      |                                                                                                         ^
In file included from /nix/store/ry265p58x5ikiq04hqqdbvdjkkwf19iz-qtbase-5.15.3-dev/include/QtNetwork/QAbstractSocket:1,
                 from src/connect/connectclient.h:25,
                 from src/connect/connectclient.cpp:18:
/nix/store/ry265p58x5ikiq04hqqdbvdjkkwf19iz-qtbase-5.15.3-dev/include/QtNetwork/qabstractsocket.h:211:10: note: declared here
  211 |     void error(QAbstractSocket::SocketError);
      |          ^~~~~
src/connect/connectclient.cpp:609:105: warning: 'void QAbstractSocket::error(QAbstractSocket::SocketError)' is deprecated: Use QAbstractSocket::errorOccurred(QAbstractSocket::SocketError) instead [-Wdeprecated-declarations]
  609 |             static_cast<void (QAbstractSocket::*)(QAbstractSocket::SocketError)>(&QAbstractSocket::error),
      |                                                                                                         ^
In file included from /nix/store/ry265p58x5ikiq04hqqdbvdjkkwf19iz-qtbase-5.15.3-dev/include/QtNetwork/QAbstractSocket:1,
                 from src/connect/connectclient.h:25,
                 from src/connect/connectclient.cpp:18:
/nix/store/ry265p58x5ikiq04hqqdbvdjkkwf19iz-qtbase-5.15.3-dev/include/QtNetwork/qabstractsocket.h:211:10: note: declared here
  211 |     void error(QAbstractSocket::SocketError);
      |
```

**Comment by albar965** [comment]
These are deprecation warnings. You can silence the warnings with -Wno-deprecated-copy -Wno-deprecated -Wno-deprecated-declarations if needed.

**Comment by albar965** [comment]
Update Marble to the latest. I removed add unneeded plugins and references to the deprecated qtscript and also added:
`add_compile_options(-Wno-deprecated-copy -Wno-deprecated-declarations)` in `CMakeLists.txt` to silence most warnings.

One caveat: I compiled these changes only on Linux. Not on Windows yet.

About LNM: 
Add a file `build_options.pro` in the parent  folder of littlenavmap and atools. This is [included into the qmake build if present](https://github.com/albar965/littlenavmap/blob/d75b15c6edc2ff08e8dd2b56e8e9d53771e12b29/littlenavmap.pro#L187-L200). Add `QMAKE_CXXFLAGS += -Wno-deprecated-copy -Wno-deprecated -Wno-deprecated-declarations` to this file.

**Comment by albar965** [comment]
BTW: Development continues in atools branch `release/3.8` and `littlenavmap/2.8`.

**Comment by albar965** [comment]
Dark theme is normally created programmatically and can be overridden using `little_navmap_nightstyle.ini`. Does it conflict with a Linux window manager probably?

Once you have the files for NixOS I can attach them to the release page. Publishing these is no problem at all.

**Comment by albar965** [comment]
> Where does it look for the `little_navmap_nightstyle.ini`?

Default values are hardcoded but can be overridden by changing the ini file which is created on first install:

https://github.com/albar965/littlenavmap/blob/master/src/gui/stylehandler.cpp#L243-L280

**Comment by albar965** [comment]
Settings folder like `C:\Users\YOURUSERNAME\AppData\Roaming\ABarthel` on Windows.

**Comment by albar965** [comment]
Yes, it's created on startup.
The Night style is nothing than the default `Fusion` with changed colors. What does it look like if it does not work, BTW?

**Comment by albar965** [comment]
Sorry, I have no idea what can cause this. Just tried on a plain Ubuntu and it's working there. Also no issues on Kubuntu which I use for development.

**Comment by albar965** [comment]
Too bad. I might try this in a NixOS VM but currently busy with all kind of other stuff.
